export const TIMING = {
  GAME_OVER_DELAY: 100,
  SPLASH_DURATION: 2000,
  LINE_CLEAR_ANIMATION: 300,
};

export const REWARDS = {
  CONTINUE_BONUS: 50,
  BLOCK_PLACEMENT: 1,
  LINE_CLEAR_BASE: 10,
};

export const GAME_CONFIG = {
  GRID_SIZE: 8,
  AD_FREQUENCY: 3,
  MAX_PLAYER_NAME_LENGTH: 50,
};
