export const themes = {
  default: {
    backgroundColor: '#f9f9f9',
    filledColor: '#4a90e2',
    clearingColor: '#ff6b6b',
    boardBackground: '#ffffff',
    borderColor: '#e0e0e0',
    cellBorderColor: '#f0f0f0',
    blockBorderColor: '#ffffff',
  },
  dark: {
    backgroundColor: '#2c3e50',
    filledColor: '#9b59b6',
    clearingColor: '#f39c12',
    boardBackground: '#34495e',
    borderColor: '#7f8c8d',
    cellBorderColor: '#4a5f7f',
    blockBorderColor: '#ffffff',
  },
  forest: {
    backgroundColor: '#e8f5e9',
    filledColor: '#4caf50',
    clearingColor: '#ff9800',
    boardBackground: '#c8e6c9',
    borderColor: '#a5d6a7',
    cellBorderColor: '#dcedc8',
    blockBorderColor: '#ffffff',
  },
  ocean: {
    backgroundColor: '#e0f7fa',
    filledColor: '#00bcd4',
    clearingColor: '#ff5722',
    boardBackground: '#b2ebf2',
    borderColor: '#80deea',
    cellBorderColor: '#b2ebf2',
    blockBorderColor: '#ffffff',
  },
};
